export const div_deck = document.querySelector('#deck')
export const div_dealer = document.querySelector('#dealer')
export const div_bot = document.querySelectorAll('#bot')
export const div_player = document.querySelector('#player')
export const player_btns = document.querySelectorAll('.player-area button')